version: "3.6"

services:
  tweeter-registry:
    image: jhipster/jhipster-registry
    container_name: tweeter-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - SPRING_SECURITY_USER_NAME=$TWEETER_REGISTRY_USERNAME
      - SPRING_SECURITY_USER_PASSWORD=$TWEETER_REGISTRY_PASSWORD
      - JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=$TWEETER_REGISTRY_JWT_TOKEN
      - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS=86400
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jeromy-vandusen-obs/tweeter-config
